# Erikson Flanker Task {.unnumbered} 

This task was initially developed by @eriksen1974effects and is aimed at quantifying response inhibition. Reaction time and accuracy are said to be dependent upon a participant's ability to inhibit irrelevant information.\
You will need to build a behavioural flanker task using PsychoPy that conform to the requirements outlined below and allow you to measure reaction and accuracy for each condition.

## Design

This is a simple 'flat' design with one factor -- Congruency, and three levels:

-   Congruent -- where the central stimuli are the same as the distractor stimuli.
-   Incongruent -- where the central stimuli are different from the distractor stimuli.
-   Neutral - where the central stimuli are different from the distractor stimuli but are not expected to interfere with processing.

\* You should include more factors to change the design to test your hypothesis; you must explain your choices in the summary of the experiment.

## Experimental requirements

Your experiment must include the following:

-   A brief information and consent sheet.
-   At least 5 practice trials where feedback is given to the participants based on their performance.
-   Feedback in practice trials should be -- correct/incorrect/no-response, too slow.
-   20 trials in each condition. \* Trials, across the three conditions, should be presented in a random order

## Trial requirements:

-   The interval between trials (also known as the inter-trial-interval: ITI) should be filled with a fixation cross -- the length of time the fixation trial is on the screen should vary such that it's offset is unpredictable.
-   The target stimuli should be presented centrally.
-   The distractor stimuli should be presented peripherally.

## Use your imagination

There are several aspects of the experiment that you can change freely; this means that you will be able to test your own specific hypothesis. Here is a list of somethings you can change but it isn't comprehensive; if it isn't specified above -- you can change it.

-   Nature of the stimuli: words, pictures, letters, symbols etc.
-   Location of the stimuli: where peripheral distractors appear.
-   Nature of the task: what aspect of the target stimuli are participants asked to respond to.
