# Explain Your Experiment 

**Submit final version with complete portfolio by - [15.04.24 10am]{.underline}**

**1200 word summary explanation of your experiment**

## Instructions

Based on your chosen experiment that you have built in PsychoPy, provide a 1200-word summary by answering the questions below. This summary should explain what design decisions you have made and why you made them -- specifically what research question are you addressing with your design choices. Make sure you briefly review the available evidence that suggests that your task is underpinned by a specific neural region or network. Use the following subsections to write your summary:

-   **Aims (\~100 words).**
    -   What are the overall research aims of your experiment? What do you hope to test and find out about cognition and/or the brain from your results.
-   **Background & rationale (\~500 words).**
    -   This section should include references and provide a succinct summary of key findings in the field that have used similar experimental designs. It is important that you include here an overview of research that has linked brain structure and/or function to experiments similar to yours. Importantly, you should also provide some key theoretical rationale for your experiment.\
-   **Predictions (\~100 words).**
    -   Your predictions don't have to be comprehensive but they should include critical hypotheses - what hypothesis is the key test of your theory?
-   **Methods & design rationale (\~500 words).**
    -   Here you should outline the details of your experimental design and prcedure. It is important that you include a rationale for any decisions you made about the design structure and procedural set up. If, for example, you added another condition, or changed the nature of the stimuli systematically - explain here why you did this - what are these novel manipulations meant to test?
